service: aws-sentry-flask-example
provider:
  name: aws
  runtime: python3.7

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}

custom:
  wsgi:
    app: api.app

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-dotenv-plugin